spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=bachelor
    username: test1234
    password: test1234

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defualtZone: http://localhost:8761/eureka
